# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: radhagowthamhub/bankapp:latest
          ports:
            - containerPort: 8080
          resources:  
            requests:
              cpu: "300m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_USERNAME  
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: SPRING_DATASOURCE_PASSWORD
---
# Bank Application Service (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
---
# MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service # headless service name 
  replicas: 1  # Set to 1 unless you configure MySQL clustering
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:  
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
        resources:  
          requests:
            cpu: "400m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi" 
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
---
# MySQL Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None  # Fixed casing
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
#Creating PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec: 
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#configmap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: config
data:
  MYSQL_DATABASE: bankappdb
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
---
#secrets
apiVersion: v1
kind: Secret
metadata: 
  name: secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Test@123
  SPRING_DATASOURCE_PASSWORD: Test@123
---
#HPA
# First install metrics server using below commands
#kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#kubectl patch deployment metrics-server -n kube-system \
#  --type=json \
#  -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'
#kubectl get deployment metrics-server -n kube-system
#kubectl top nodes and kubectl top pods


 # autoscaling/v1 = scale based on CPU metrics only and autoscaling/v1 = scale based on memory, custom, and external metrics.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpaautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankapp
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10

