apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pvcName | default "mysql-pvc" }}
  labels:
    app: {{ .Values.backend.appLabel | default "mysql" }}
spec:
  storageClassName: {{ .Values.backend.storageClassName | default "standard" }}
  accessModes:
    - {{ .Values.backend.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.backend.storage | default "1Gi" }}

