apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: {{ .Values.frontend.appLabel }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.frontend.appLabel }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}

