apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.shared.secret }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{ .Values.backend.MYSQL_ROOT_PASSWORD }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.frontend.SPRING_DATASOURCE_PASSWORD }}"
